### ISSUE TITLE
Please turn on Travis tests

### ISSUE THREAD

**Issue by talex5** [pelzlpj/capnp-ocaml#20]
This repository contains a Travis file which can automatically test each PR (#10), but it needs to be turned on for this repository. It's free, but only the repository owner can enable it:

1. Go to https://travis-ci.org/
2. Log in (with GitHub login)
3. Go to Accounts in the user menu
4. Click the toggle next to the capnp repository

All future PRs will then be tested automatically.

Thanks,

**Comment by pelzlpj** [comment]
Done!
